### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by Pyromanc3r** [CrossVas/GraviSuiteReforged-1.5.2#5]
https://mclo.gs/ihdWI0D

**Comment by CrossVas** [comment]
Can you please check the latest release?

**Comment by Pyromanc3r** [comment]
Looks like it's working. But I found the Gravitation Chestplate to behave strangely. This allows you to levitate even if the option "Levitation mode" is not enabled. It also protects against fall damage (which is supposed to require QuantumSuit Boots).
Also I can't fly with the QuantumSuit Bodyarmor from the basic IC2. Armor is charged, but the character does not take off. I think I've tried all the key combinations. A regular Jetpack allows you to fly. Hover Mode ("Mode Switch Key" + "Space") also works. Is this an IC2 bug or is there some special key combination needed?

And a slightly off-topic question. Which version of IC2 is better to use for Gregtech? A warning pops up in the game that you need downgrade to 1.116.377-lf (there are some problems with the power system), while on Greg's site it says that version 1.117.385-lf is required. Who to believe? I also found version 1.117.921, but I couldn’t find the changelog (the IC2 repository is dead).

**Comment by Pyromanc3r** [comment]
In short, Gravitation Chestplate gives you flight like in creative mode and removes fall damage. Double jump to activate flight. "Levitation mode" is ignored.

**Comment by CrossVas** [comment]
Didn't quite understand the first part. 
IC2 QuantumSuit on version pre-experimental (which is 1.5.2 and bellow) didn't provide flight ability. 
Now to explain how `Gravitational Chestplate` works:
By default you have 2 options. 
1. You can toggle `creative`-like fly mode by pressing `Armor Toggle Key`, `F` by default. This will give you creative flight, will remove any fall damage at the energy cost. To fly you perform a double jump. 

2. If you're tired of doing double jumps, you can enable `Levitation Mode`, this mode allows you to take off whenever `Antigravity Engine` is on. So instead of doing double jump, you just enable `Levitation Mode` and then by pressing `Armor Toggle Key`, you take off instantly. 
![image](https://github.com/CrossVas/GraviSuiteReforged/assets/25727222/7acca533-f35c-47a4-9bbf-455d146dc456)

UPD:
This is how `Gravitational Chestplate` worked on version 1.6.4 and 1.7.10. On version 1.12.2 it got deprecated and provided only creative flight with no levitation.

**Comment by CrossVas** [comment]
> And a slightly off-topic question. Which version of IC2 is better to use for Gregtech? A warning pops up in the game that you need downgrade to 1.116.377-lf (there are some problems with the power system), while on Greg's site it says that version 1.117.385-lf is required. Who to believe? I also found version 1.117.921, but I couldn’t find the changelog (the IC2 repository is dead).

With version `1.116.377-lf` IC2 team started transitioning to `Experimental` port, starting with `EnergyNet` re-work, which caused issues with the way `GregTech` handled things and thus a warning was provided. I personally play with `1.116.377-lf` and don't care about versions above it.

**Comment by Pyromanc3r** [comment]
> IC2 QuantumSuit on version pre-experimental (which is 1.5.2 and bellow) didn't provide flight ability.

Now that explained a lot. Apparently that’s why in those days there was a need for the `Gravitation Suite` addon.

> Gravitational Chestplate will remove any fall damage at the energy cost

This is strange because `QuantumSuit Boots` should be responsible for this. If you put on boots and take off with a regular Jetpack and fall, you will not take damage. Boots absorb damage. But okay, if that's how it's meant to be, then so be it.

> I personally play with 1.116.377-lf

I understand. So there's nothing to worry about. Thank you.

I think this issue can now be closed.

**Comment by CrossVas** [comment]
> This is strange because `QuantumSuit Boots` should be responsible for this. If you put on boots and take off with a regular Jetpack and fall, you will not take damage. Boots absorb damage. But okay, if that's how it's meant to be, then so be it.

Actually, this might change. I should consult the original 1.4.7 mod description and adjust features. For now it'll be this way.
https://forum.industrial-craft.net/thread/6915-ic2-exp-1-7-10-gravitation-suite-v2-0-3/
