### ISSUE TITLE
GUI positions issue

### ISSUE THREAD

**Issue by Pyromanc3r** [CrossVas/GraviSuiteReforged-1.5.2#6]
I found a small bug with the GUI. If you change the position of the indicators in `hud_pos=3`, the "Energy level" line is duplicated. Also, the "X Pos" and "Y Pos" parameters don't seem to work. The lines don't shift.
![position_bug](https://github.com/user-attachments/assets/14840fa3-1b8c-439c-82fa-a762db4b70b5)

I also made a localization file and it would be nice to add it. I know that it can be included as an external file, but I think it will be easier this way.
[ru_RU.zip](https://github.com/user-attachments/files/17066177/ru_RU.zip)

**Comment by CrossVas** [comment]
Thanks. I'll look into it.

**Comment by CrossVas** [comment]
Okay, the duplication line is fixed. 
As for the `X/Y Pos` this has a separate config option that needs to be changed to false in order for it to work.
```
    # Should GraviSuite HUD use fixed values from below? // referencing hud_pos
    # Default: true
    B:enable_hud_fixed=false
``` 
![image](https://github.com/user-attachments/assets/8184d482-2198-4da8-a9f4-1bf47bfb6117)

### Translation
```
message.tool.mode.vein_extended=Связующие 129 блоков
```
This I'll change to `Расширенная жила`, because the amount might change in the future. Maybe I'll add a config value, not decided yet.
```
message.vein.active=Активирован режим добычи всей рудной жилы
```
This I'll change to `Активный режим добычи рудной жилы`

```
message.tool.mode.vein=Вся рудная жила
```
Same here: `Рудная жила`

```
message.info.quick_change=[!] Быстрое переключение в режим парения [!]
```
This works both ways. From `Hover` to `Normal` and vice-versa.
I'll change it to: `Быстрое переключение режимов`

Also, Jetpacks don't have `Режим Левитации`, it's `Режим Парения`
![image](https://github.com/user-attachments/assets/a77f6c66-8ffd-4f96-a49a-67c3373b63d5)

You can try this build: https://github.com/CrossVas/GraviSuiteReforged/releases/tag/2.2.2n
I hope I didn't miss anything :D
Thanks for contribution!
